# Generated by Django 5.2.6 on 2025-11-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('frame_image', models.ImageField(upload_to='frames/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
