# Generated by Django 5.2.6 on 2025-11-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
