# Generated by Django 5.2.8 on 2025-11-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Twibbon Lombok Barat', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
        ),
    ]
